### ISSUE TITLE
Consider adding screenshots/gifs to quickly demonstrate the themes UI

### ISSUE THREAD

**Issue by JustinBeaudry** [google/typedoc-neo-theme#1]
The first thing I (personally) want to see when I navigate to a documentation theme repo is what the theme looks like. Would be nice if there were some screenshots/gifs added to do just that.

**Comment by Fleker** [comment]
Thanks for the suggestion. We're preparing a set of content that will accompany the project. In the short-term, you can browse the [Actions on Google docs](https://actions-on-google.github.io/actions-on-google-nodejs/), which are generated with this theme.
