### ISSUE TITLE
Cannot find module @gerrit0/typedoc

### ISSUE THREAD

**Issue by ozum** [google/typedoc-neo-theme#10]
When using theme, I got following error:

```
Error: Cannot find module '@gerrit0/typedoc/dist/lib/converter/components'
Require stack:
- .../node_modules/typedoc-neo-theme/bin/default/plugin.js
```

When I tracked the issue, I found in `plugin.ts`

```ts
import { Component, ConverterComponent } from '@gerrit0/typedoc/dist/lib/converter/components'
```

However `@gerrit0/typedoc` is not listed by any dependencies in `package.json`. 

Should it be

```ts
import { Component, ConverterComponent } from 'typedoc/dist/lib/converter/components'
```

or `@gerrit0/typedoc` added to dependencies?

Thanks,

**Comment by Fleker** [comment]
Looks like yarn had cached the dependency when I switched to the mainstream Typedoc dependency.

**Comment by Mateiadrielrafael** [comment]
# Was this fixed? 
It seems like it was, so why keep it open?

**Comment by Fleker** [comment]
Small bug with a not-entirely-clean yarn.lock
