### ISSUE TITLE
Links in left side outline are incorrectly transformed to remove surrounding _ _

### ISSUE THREAD

**Issue by crucialfelix** [google/typedoc-neo-theme#11]
Building with:

`lang ❯ typedoc --theme /Users/crucialfelix/.nvm/versions/node/v10.15.1/lib/node_modules/typedoc-neo-theme/bin/default`

(globally installed neo-theme)

creates a front page:
`file:///Users/crucialfelix/code/supercolliderjs/docs/packages/lang/docs/index.html`

The generated source contains items in `.tsd-navigation-primary` that populate the sidebar:

```
<li class=" tsd-kind-external-module">
  <a href="modules/_sclang_.html" style="display:none">sclang</a>
</li>
```

These links are correct (but invisible). Each module is surrounded with `_`modulename`_`.html

But this is then rendered to the DOM (by frontend javascript AFAICT) as:

`<a href="modules/sclang.html">sclang</a>`

ie:
`file:///Users/crucialfelix/code/supercolliderjs/docs/packages/lang/docs/modules/sclang.html`

*Without* the surrounding underscores.  Which is 404

**Comment by Fleker** [comment]
Are you using a [custom outline](https://github.com/google/typedoc-neo-theme#outline)?

**Comment by Fleker** [comment]
Seems to be happening [here](https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/assets/js/src/typedoc/components/NavigationAccordion.ts#L99).

As clients typically use a custom outline, I suppose this issue hasn't really been noticed.

**Comment by rxliuli** [comment]
It's already December. Will this problem be fixed?

**Comment by Fleker** [comment]
This is being addressed in a pull request. Attached is an auto-generated package that you can use to try out right away.
[a1250f0_typedoc-neo-theme-1.0.4.zip](https://github.com/google/typedoc-neo-theme/files/3990143/a1250f0_typedoc-neo-theme-1.0.4.zip)

**Comment by rxliuli** [comment]
After actual measurement, the above zip package still has some problems. I tried to modify some code and fixed this problem (I did not understand the compilation process of the entire theme)

Behavior of the above zip package

The link on the homepage sidebar is normal

![image](https://user-images.githubusercontent.com/24560368/71303433-98743880-23f3-11ea-9043-05974fc9afdb.png)

Subpage

![image](https://user-images.githubusercontent.com/24560368/71303459-fdc82980-23f3-11ea-8245-83206933e53c.png)

The part I modified (relative to `node_modules/typedoc-neo-theme`)

![image](https://user-images.githubusercontent.com/24560368/71303413-4b906200-23f3-11ea-875e-cc2674e9d67a.png)

Compressed a modified

[typedoc-neo-theme.zip](https://github.com/google/typedoc-neo-theme/files/3991075/typedoc-neo-theme.zip)
