### ISSUE TITLE
--style=compact should be --style=compressed

### ISSUE THREAD

**Issue by jpoehnelt** [google/typedoc-neo-theme#13]
`"compact" is not an allowed value for option "style".`

https://sass-lang.com/documentation/cli/dart-sass#style

https://github.com/google/typedoc-neo-theme/blob/cf20a30332eafccf5b91bf67873affbccb609d19/third_party/gruntfile.js#L57

**Note:** `unixNewlines` has the same issue.

**Comment by Fleker** [comment]
What version of SASS are you using?

**Comment by Fleker** [comment]
On my system `sass --version` returns `Ruby Sass 3.7.3`.

If there's a different version, with different options, I may need to update the field or make the README more specific.

**Comment by jpoehnelt** [comment]
I used `npm install -g sass` from https://sass-lang.com/install. 

>However, please note that this will install the pure JavaScript implementation of Sass, which runs somewhat slower than the other options listed here. But it has the same interface, so it’ll be easy to swap in another implementation later if you need a bit more speed!

```
sass --version
1.23.2 compiled with dart2js 2.5.2
```
Seems like your version is deprecated?

>Ruby Sass was the original implementation of Sass, but it reached its end of life as of 26 March 2019. It's no longer supported, and Ruby Sass users should migrate to another implementation.

https://sass-lang.com/ruby-sass

**Comment by Fleker** [comment]
Hmm looks like a larger migration will be needed.
