### ISSUE TITLE
Navigation link error after using theme

### ISSUE THREAD

**Issue by rxliuli** [google/typedoc-neo-theme#16]
After a closer look, the initial HTML returned was correct

Before use

If you don't use `typedoc-neo-theme`, the link is normal. It seems that` typedoc-neo-theme` does something. . .
![image](https://user-images.githubusercontent.com/24560368/70954763-786a0f80-20a9-11ea-93d4-5b96a1eceba7.png)

---

After use

After a closer look, the initial HTML returned was correct
![image](https://user-images.githubusercontent.com/24560368/70954668-1b6e5980-20a9-11ea-9a33-90187d709284.png)

But it changed after `main.js` was run, and I don't know what happened. . .
![image](https://user-images.githubusercontent.com/24560368/70954616-f11c9c00-20a8-11ea-8d31-94ebce8bd857.png)
![image](https://user-images.githubusercontent.com/24560368/70954702-3d67dc00-20a9-11ea-94de-24eb6ca65320.png)

I have communicated under typedoc before, but it feels like it should be a topic issue. . .

> Reference: <https://github.com/TypeStrong/typedoc/issues/1147>

**Comment by Fleker** [comment]
Does the sidebar work before if you put [a custom outline](https://github.com/google/typedoc-neo-theme#outline) in your `typedoc.json` file?

**Comment by rxliuli** [comment]
It can be generated normally, but must be specified as the following configuration

```js
"outline": [
  {
    "ajax": {
      "download": "_module_ajax_download_",
      "downloadString": "_module_ajax_downloadstring_"
    }
  }
],
```

It should be where the theme is wrong, the complete configuration is as follows

```json
{
  "out": "docs",
  "include": "src",
  "exclude": "src/**/*.test.ts",
  "ignoreCompilerErrors": true,
  "theme": ["./node_modules/typedoc-neo-theme/bin/default"],
  "plugin": ["./node_modules/typedoc-neo-theme/bin/default/plugin.js"],
  "links": [
    {
      "label": "GitHub",
      "url": "https://github.com/rxliuli/rx-util"
    },
    {
      "label": "Author",
      "url": "https://rxliuli.com/"
    }
  ],
  "outline": [
    {
      "ajax": {
        "download": "_module_ajax_download_",
        "downloadString": "_module_ajax_downloadstring_"
      }
    }
  ],
  "source": [
    {
      "path": "https://github.com/rxliuli/rx-util/blob/dev/",
      "line": "L"
    }
  ]
}
```

**Comment by rxliuli** [comment]
The error here is that all the outlines are deleted from the `window.onload` function in main.js, and then regenerated using the `renderSimpleHTMLRecursive` function, but the generated outlines are problematic!

![image](https://user-images.githubusercontent.com/24560368/71135397-75535880-223c-11ea-9d99-efe65676d2b1.png)

**Comment by rxliuli** [comment]
> It seems that this issue has already been mentioned: <https://github.com/google/typedoc-neo-theme/issues/11>

**Comment by Fleker** [comment]
Follow in #11
