### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by Mateiadrielrafael** [google/typedoc-neo-theme#2]
I have a module called `rxjs-bits`, and the link points to rxjs-bits.html, while it should point to rxjs_bits.html. Works fine with the default theme.

**Comment by Fleker** [comment]
You're referring to the left-hand side? Are you using a custom outline?

**Comment by Mateiadrielrafael** [comment]
Yeah, i was talking about the left hand side. I don't know what a custom outline is. @Fleker

**Comment by Fleker** [comment]
This theme adds a way to [manually specify the left-hand side](https://github.com/google/typedoc-neo-theme#outline).

**Comment by Mateiadrielrafael** [comment]
It worked perfectly, I'll close this!

**Comment by Fleker** [comment]
So the default theme generates in snake_case while the left-hand navigation uses dash-case? Seems like something to be resolved generally.

**Comment by Mateiadrielrafael** [comment]
@Fleker yes, that's exactyl what happens!  Manually specifying the outline gave me much more flexibility so I'll stick with that.

**Comment by Fleker** [comment]
May be a [part of this](https://github.com/TypeStrong/typedoc/blob/14d23b8f13ec9f432ce88c1514326be459af3ccf/src/lib/models/reflections/abstract.ts#L436) sanitizer, which gets called in part by the relativeURL helper that I've omitted.
