### ISSUE TITLE
Can I use tools such as prettier to uniformly format the configuration?

### ISSUE THREAD

**Issue by rxliuli** [google/typedoc-neo-theme#23]
I currently use WebStorm to modify the JS / TS code, but the trouble is that I don't know what the configuration format of your code is, and everyone's configuration may be different?
Perhaps, where can I find Google's code specification configuration files, including WebStorm / VSCode?

> Ref link：<https://prettier.io/>

**Comment by Fleker** [comment]
Right now there is no formal style. At some point I will want to switch to Google's [ESlint](https://github.com/google/eslint-config-google), but right now that's not a requirement necessarily.

**Comment by rxliuli** [comment]
The main problem is that there is no uniform code style. I must carefully select the code block I modified and then format it. I also check whether the unrelated code is modified because of formatting. The problem is not Linter but Code formatter.

![image](https://user-images.githubusercontent.com/24560368/71997219-7ba38600-3278-11ea-85aa-116b11a42217.png)

**Comment by rxliuli** [comment]
Honestly, I'm not even sure if this project has a unified code style inside Google, because the indentation of the upper and lower functions is not consistent. . .

![image](https://user-images.githubusercontent.com/24560368/71997492-ea80df00-3278-11ea-98ee-c2ffe2b1d8e1.png)

**Comment by rxliuli** [comment]
![image](https://user-images.githubusercontent.com/24560368/71997831-7bf05100-3279-11ea-9d20-bf1c4c301e03.png)

**Comment by Fleker** [comment]
Yes I agree that the lack of a uniform standard is not ideal. A linter would help catch problems and set a standard. Google does have a [Typescript](https://github.com/google/gts) prettifier and [style guide](https://google.github.io/styleguide/jsguide.html), although I recognize this project isn't guaranteed to follow it right now.
