### ISSUE TITLE
Not working in the following environment

### ISSUE THREAD

**Issue by wgtgithub** [google/typedoc-neo-theme#29]
`ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.4
Node: 10.16.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.8.9
@angular-devkit/build-optimizer    0.8.9
@angular-devkit/build-webpack      0.8.9
@angular-devkit/core               0.8.9
@angular-devkit/schematics         7.3.4
@angular/cdk                       7.3.7
@angular/cli                       7.3.4
@angular/compiler-cli              7.2.7
@angular/language-service          7.2.7
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   6.2.9
@schematics/angular                7.3.4
@schematics/update                 0.13.4
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.16.4`

**Comment by Fleker** [comment]
What does it mean to not be working?

**Comment by wgtgithub** [comment]
just fault to install this plugin into the above ng conditions

**Comment by Fleker** [comment]
So Typedoc isn't working? Or is the theme not working in particular?

**Comment by wgtgithub** [comment]
Typedoc is working before installed this plugin and after uninstalled the plugin also
I should restore package.json at uninstalled the plugin because happened node error for that
Don't worry I give up to use this plugin in our environment

**Comment by Fleker** [comment]
What error do you get? I don't understand what you're doing and what problem you're getting?

**Comment by wgtgithub** [comment]
Don't worry puzzled you, actually this plugin is not working for Angular 7
But it is not your matter, that's mine, OK?

**Comment by Fleker** [comment]
This is unrelated to Angular.
