### ISSUE TITLE
Overflowing issues on mobile

### ISSUE THREAD

**Issue by JanMalch** [google/typedoc-neo-theme#3]
The main navigation and the index list is overflowing, causing the page to be zoomed out on mobile.

**Comment by Fleker** [comment]
Can you share a screenshot of what you mean?

**Comment by JanMalch** [comment]
Here you can see how both the top navigation aswell as the index list is overflowing.

![image](https://user-images.githubusercontent.com/25508038/66846542-3ec63c80-ef72-11e9-8a21-b9a1c94f7f33.png)

I added these [two lines in my fork](https://github.com/JanMalch/typedoc-neo-theme/commit/2ca4266724fbf6a06cb0b9a060baa90ea5f87093) to fix the index list, but haven't found a solution for the main navigation yet, as the HTML is more complicated.

**Comment by Fleker** [comment]
Seems like a problem that will take a fair amount of CSS to adjust.
