### ISSUE TITLE
Comment short text causing duplicate param/returns/type values

### ISSUE THREAD

**Issue by ThePuzzlemaker** [google/typedoc-neo-theme#30]
Hello. I have noticed that on this theme, there are duplicate comment tags. For example, due to comments' short text being rendered into the documentation, the following code:
```ts
  /**
   * Connect to this store's respsective database
   * @returns Was able to connect?
   */
  abstract connect: () => Promise<boolean>;
```
creates this documentation, which contains duplicate `@returns` sections due to the inclusion of both short text and tags:
![Documentation example](http://0x0.st/izSe.png)
Is there any way to solve this with some sort of configuration option?
TypeScript version: 3.7.5
TypeDoc version: 0.16.9
TypeDoc Neo Theme version: 1.0.5
Here's my TypeDoc configuration, in case that helps.
```json
{
    "mode": "modules",
    "out": "docs",
    "externalPattern": "node_modules/**/*.ts",
    "excludeExternals": true,
    "includeDeclarations": true,
    "theme": "./node_modules/typedoc-neo-theme/bin/default",
    "name": "DBPMStore Documentation",
    "includeVersion": true,
    "hideGenerator": true,
    "plugin": "typedoc-neo-theme"
}
```

**Comment by Fleker** [comment]
That seems like a general theme bug

**Comment by bmight** [comment]
I am also getting this issue with `@name` and `@path` tags. 

TypeScript version: 3.2.4
TypeDoc version: 0.16.11
TypeDoc Neo Theme version: 1.0.6

**Comment by bmight** [comment]
Having a hard time currently getting the build to work on windows so I can't make a PR. I'll see if I can take a look later tonight.

I think the issue is here: https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/partials/comment.hbs#L33

Tags get added within shorttext and text blocks then again at the bottom of the comment. Not sure if it's better to remove the tags from shorttext and text blocks or change up the conditional logic.

**Comment by Fleker** [comment]
Ah it may be something to do with 7b0dc6c000b69e00606af7d1ecc90076fd50c6d6

I've been building on Linux primarily, but WSL should work just as well.

**Comment by bmight** [comment]
Yeah I broke my WSL container recently but I can reinstall and create a PR tonight if you want.

I was planning on just removing the tag sections out of `tsd-comment-shorttext` and `tsd-comment-text` then leaving the tag section at the bottom. Thoughts?

**Comment by Fleker** [comment]
Yeah I think that should work. I'd like to start building up an example project for regression testing at some point soon too.

**Comment by gtamas** [comment]
@Fleker @bmight 
I'm still seeing duplicated comments and I'm using 1.0.7. 
I guess the issue is not resolved yet..

Sometimes even @example tags appear to be duplicated
