### ISSUE TITLE
Some issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by FStefanni** [google/typedoc-neo-theme#31]
Hi,

I tried this nice theme to document a custom node-red node, but I have found some issues.

# Issue 1: wrong file names/links

My module has a neme (and it is into a directory) with a form as "my-module".
Files generated by typedoc are in the form "_my_module_otherstuff.html".
Links on the left of the page (in the navigation menu) are like: "_my-module_otherstuff.html" (please note the "-" vs "_").

Since with the default theme I have not this issue, I believe this could be a problem of your theme.
If not, please let me know so I'll open an issue on the typedoc issue tracker.

# Issue 2 Wrong rendering of left side menu

Since the list of left menu entries is very long, it goes over the footer, as shown in the image.

![typedoc-issue](https://user-images.githubusercontent.com/33950786/73730648-69155300-4737-11ea-93e5-fc6a06fd7028.png)

I have opened the browser developers console, and I have seen the following error:

`TypeError: this.$navigation.offset(...) is undefined`

Maybe the rendering problem is related to this error.
I am using Ubuntu 18.04 with the latest packages, Firefox 72.0.2 (64-bit), typedoc 0.16.9, typedoc-neo-theme 1.0.5.

By the way, I have installed the theme with the command:

`npm install typedoc-neo-theme`

and I generate the doc with:
```
node_modules/.bin/typedoc \
    --options doc/typedoc.json      \
    --theme ./node_modules/typedoc-neo-theme/bin/default \
    --plugin typedoc-neo-theme
```
Maybe am I missing something?

Thank you for your help.
Regards.

**Comment by Fleker** [comment]
Re issue 1, the fix should be replacing `-` with `_` so the filename is correctly `my_module...`?

Re issue 2, do you want all of the fields to be directly placed in the left-hand side menu, or would you want to replace that with a more organized navigation?

**Comment by FStefanni** [comment]
Thank you for the reply.


### 1

Yes: in the left menu links, replace  "-" with "_".

This because all the other references works (by using all "_"). Only the left menu seems broken.

### 2

Sorry, I did not explained myself well.
As shown in the figure, the left-side menu items (in the figure "jsonMqttPacket", "jsonMqttResult"), are going over the page footer, overlapping with the footer content (in the figure, the footer is from the gray line to below, and contains the writing "Generated using TypeDoc").

The expected behavior should be one to have no overlapping between the page content (in this case, the menu items), and the footer.

One of the following solutions are possible:

1. The page became very long, in order to accommodate all the  menu items.
2. Make the menu items scrollable, so that when they do not fit anymore, became hidden without overlapping with the footer.

The second solution is obviously the best.
At the moment, the second solution seems the implemented behavior (the menu already scrolls!), but somehow it scrolls partially overlapping with the footer. 

After having fixed the scrolling behavior, a better left menu organization could help to improve usability (e.g. collapsible/expandable items).

Regards.

**Comment by Fleker** [comment]
For Part 1, can you try out the package from PR #35?

[pr-35.zip](https://github.com/google/typedoc-neo-theme/files/4251330/pr-35.zip)

**Comment by Fleker** [comment]
With regards to the second, I'm not sure I can reproduce the overlap issue. Using the AoG library as a reference, without a custom outline, it uses the `.tsd-navigation` class in order to take up a subset of the page and include scrollbars.

**Comment by Fleker** [comment]
![Screenshot from 2020-02-25 12-53-00](https://user-images.githubusercontent.com/3291635/75274084-2e4f8980-57d0-11ea-8411-74a484965a72.png)

**Comment by FStefanni** [comment]
#1 

The pr seems to work fine to me :)
I'll wait the upcoming release to contain this fix. 
Thank you.

# 2

Re-tested and now... I have no more the issue (by using the officially released theme, not the pr -- but also the pr works fine).

Maybe it is because I have upgraded some packages in the meantime:
* typedoc 0.16.10
* firefox 73.0

It still gets the error if I open the console:
```
TypeError: this.$navigation.offset(...) is undefined
```
So clearly this error was not the cause of the issue.
But ok, what matters is that it is now working.

thank you for your support.

**Comment by Fleker** [comment]
v1.0.6 has been released.
