### ISSUE TITLE
Regression with Outline menu

### ISSUE THREAD

**Issue by o0Djeen0o** [google/typedoc-neo-theme#33]
Hi,

I wanted to upgrade to release `1.0.5`, but there seems to be an issue with the way urls contained in the outline menu are now computed. This behavior happens when using references to resources which are not `modules`.

Here is an example of an outline definition.

```
"typedocOptions": {
        "out": "docs",
        "name": "My Documentation",
        "readme": "README.docs.md",
        "mode": "modules",
        "outline": [
            {
                "Main menu": {
                    "Something with classes": {
                        "Link 1": "classes/<suffix>"
                    }
                }
            }
        ]
    }
```

From `index.html`, if I click on the link, it will redirect to something like `<base-url>/classes/<suffix>.html`
But then, clicking again on the same link from this page will then redirect to a wrong url, using `modules` path like `<base-url>/modules/classes/<suffix>`

In `1.0.4`, it was working perfectly fine. 
Maybe related to this change :
https://github.com/google/typedoc-neo-theme/pull/20/files#diff-301d30ef180768244bd2d94c66dc9dc9R460
Could you help ?

**Comment by Fleker** [comment]
Yeah it looks like the directory is selected incorrectly.

**Comment by o0Djeen0o** [comment]
HI @Fleker,

I've tested your package with my pipeline and it resolves the relative links issues as expected. Thanks !
