### ISSUE TITLE
Menu sublinks not working

### ISSUE THREAD

**Issue by FStefanni** [google/typedoc-neo-theme#40]
With typedoc mode set to "file" everything is ok.
But with typedoc mode set to "modules" menu links work only in the index page.
In fact, the URL seems missing the "modules" path.

Example:
1. Open *doc/html/index.html*: click over a left hand side menu item
1. This opens *doc/html/**modules**/_myclass1_.html*: perfect. Clik now on another item.
1. This opens *doc/html/_myclass_2.html*: wrong, it misses the "modules" part form the URL.

Tested with:
* typedoc 0.16.11
* typedoc-neo-theme: 1.0.6

Regards.

**Comment by Fleker** [comment]
Can you test with 1.0.5? I fear this may have been a regression.

**Comment by FStefanni** [comment]
I have done a quick test, but actually it seems to fail also with 1.0.5.

**Comment by Fleker** [comment]
Can you specify how to put the typedoc mode to "modules"? It does not [appear to be the default mode](https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/typedoc.json).

**Comment by e-r-w** [comment]
@Fleker you can put typedoc into `modules` mode by [specifying the `mode` flag](https://typedoc.org/guides/options/#mode)

Looks like [this here](https://github.com/google/typedoc-neo-theme/commit/51e5101d334d8dfeef31a21e4120e8b462104821#diff-301d30ef180768244bd2d94c66dc9dc9R441) is the offending line of code. I'll send through a PR shortly!
