### ISSUE TITLE
Update to 1.0.7

### ISSUE THREAD

**Issue by bmight** [google/typedoc-neo-theme#43]
Do we have a rough ETA when #41 will be pushed to npm at version 1.0.7?

Thanks!

**Comment by Fleker** [comment]
I'll say Thursday at the latest. I would like to spend a bit of time seeing if I can write a test or two to prevent regressions.

**Comment by bmight** [comment]
@Fleker Thanks! The theme is awesome.

**Comment by Fleker** [comment]
[It's been published](https://github.com/google/typedoc-neo-theme/releases/tag/v1.0.7)
