### ISSUE TITLE
JavaScript error in MenuSticky causes some other components not to work 

### ISSUE THREAD

**Issue by blutorange** [google/typedoc-neo-theme#47]
An JavaScript error in `MenuSticky.ts` results in some components such as Signature not being initialized:

* For method overloads, it's normally possible to click on an overload to show the documentation for that overload. But because of the JavaScript error, all method overloads are shown at the same time, which makes it pretty hard to read.

Seems to be caused by [a wrong selector for the $navigation element](https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/assets/js/src/typedoc/components/MenuSticky.ts#L75), which selects no element. Later, [the offset of that element](https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/assets/js/src/typedoc/components/MenuSticky.ts#L137) is `undefined`, and accessing the property `left` of `undefined` results in an error.

# How to reproduce

Go to [actions-on-google-nodejs](https://actions-on-google.github.io/actions-on-google-nodejs/2.12.0/index.html) and open the dev tools:

![image](https://user-images.githubusercontent.com/2456413/77852055-d34cf000-71dc-11ea-83f9-9f7261b39e80.png)

**Comment by Fleker** [comment]
If it is set to `this.$el` then it appears to work successfully

**Comment by jgroh9** [comment]
I know this is closed and the PR has been merged into master but there needs to be a new build, tag, and release created with this fix. Any idea when that might happen?

**Comment by Fleker** [comment]
Tomorrow
