### ISSUE TITLE
Duplicated CodeBlock

### ISSUE THREAD

**Issue by pchuong** [google/typedoc-neo-theme#49]
When using the code block syntax, the out contains duplicated code block.

For example:

```javascript
var str = 'helloWorld!';
```

Generates "var str = 'helloWorld!'" twice.

**Comment by Fleker** [comment]
This is on v1.0.7?

Can you provide a slightly larger example of when this happens?

**Comment by pchuong** [comment]
I found what the issue is, if I don't have an blank line between "Awesome package." and "```javascript", it works. Works in the the example below. However, if there is a blink line in between, than I see the duplicated code block.

/**
 * Awesome package.
 * ```javascript
 * const str = 'helleWorld!';
 * ```
 *
 * @packageDocumentation
 */

**Comment by Fleker** [comment]
I'm not reproducing this at master, so it may have been fixed by #48.

**Comment by Fleker** [comment]
Can you try on v1.0.8 if that behavior still occurs?

**Comment by pchuong** [comment]
I can reproduce the issue with v1.0.8.

**Comment by Fleker** [comment]
Should be fixed by #51. Can you verify against the build?

[a57cc40_typedoc-neo-theme-v1.0.8.tar.zip](https://github.com/google/typedoc-neo-theme/files/4483743/a57cc40_typedoc-neo-theme-v1.0.8.tar.zip)

**Comment by pchuong** [comment]
I update to v1.0.8 using NPM and this issue is resolved. Thanks!

**Comment by pchuong** [comment]
I updated to v1.0.8 with npm, the issue still exist.
