### ISSUE TITLE
References dont work

### ISSUE THREAD

**Issue by Mateiadrielrafael** [google/typedoc-neo-theme#5]
Usually with other themes I could just do `[[remove]]``` and then I got a link poiting to the correct part of the page. Using this theme I get this: 
![image](https://user-images.githubusercontent.com/39400800/66923018-cbcfcb00-f030-11e9-9d0a-1ecab7563e74.png)

**Comment by Fleker** [comment]
Can you be specify where you add that, and what you expect to happen?

**Comment by Mateiadrielrafael** [comment]
So basically if i had a method called `foo` and i wrote `[[foo]]` in a comment it created a link which pointed to the docs for that method (eg: http://a.b/classes/something#foo)

**Comment by Fleker** [comment]
Is this something that was in the original theme? I don't think I removed something like this, but could also add it in.

**Comment by Mateiadrielrafael** [comment]
@Fleker I think it was also caused by the old relative urls problem. I guess we can close it for now.
