### ISSUE TITLE
Typedoc 0.17 upgrade

### ISSUE THREAD

**Issue by o0Djeen0o** [google/typedoc-neo-theme#53]
Hi,

Typedoc 0.17 has been released for a while now, with support for interesting features (like type only imports). I wanted to know if upgrade was on its way for this plugin ?

For instance, there is right now a dependency in `package.json` which fixes typedoc to `0.16` branch:
https://github.com/google/typedoc-neo-theme/blob/master/package.json#L30

Thanks for your help and best regards.

**Comment by Fleker** [comment]
They just put out [0.17.7](https://github.com/TypeStrong/typedoc/releases/tag/v0.17.7), so it is time to look at updating and resolving any potential upgrade issues.
