### ISSUE TITLE
@category is ignored

### ISSUE THREAD

**Issue by airtonix** [google/typedoc-neo-theme#63]
Looks like `@category` is being ignored.

our code:
```
...
 *
 * @export
 * @abstract
 * @category Mobx-Keystone Model
 * @class BaseModel
 * @extends {Model}
 */
```

In the default theme: 
![image](https://user-images.githubusercontent.com/61225/101125595-81047e80-3649-11eb-93c7-f66ce3f1c848.png)

In the NeoTheme, this `Mobx-Keystone Model Classes` area is no where to be found.

**Comment by Fleker** [comment]
Looks like the default theme added it in https://github.com/TypeStrong/typedoc-default-themes/pull/61. Might be as easy as cherry-picking that change.
