### ISSUE TITLE
Problem with the new version of Typedoc (0.20.x)

### ISSUE THREAD

**Issue by niquenen** [google/typedoc-neo-theme#66]
[New versions of Typedoc](https://github.com/TypeStrong/typedoc/releases) (`0.20.x`) are available since few days.

Since this update I have problems with the generation of the documentation with several errors. However, if I use Typedoc version `0.19.2` everything is fine. I tried with the default theme and there were no errors when generating the documentation.

Output when I used Typedoc version `0.20.5`:
```console
Info: Loaded plugin typedoc-neo-theme
Error: Tried to set an option (mode) that was not declared.
Error: Tried to set an option (includeDeclarations) that was not declared.
Error: Tried to set an option (entryPoint) that was not declared.
Error: Tried to set an option (excludeNotExported) that was not declared.
Error: Tried to set an option (stripInternal) that was not declared.
Error: Tried to set an option (ignoreCompilerErrors) that was not declared.
```
---
I use the following command to launch Typedoc:
```shell
typedoc	--options typedoc.json --tsconfig tsconfig.json
```

This is my Typedoc configuration:
```json
{
    "mode": "modules",
    "includeDeclarations": false,
    "entryPoint": "",
    "excludeExternals": false,
    "excludeNotExported": false,
    "excludePrivate": false,
    "excludeProtected": false,
    "stripInternal": false,
    "ignoreCompilerErrors": true,
    "media": "",
    "includes": "",
    "out": "docs",
    "theme": "./node_modules/typedoc-neo-theme/bin/default",
    "name": "PROJECT NAME",
    "includeVersion": true,
    "readme": "none",
    "categorizeByGroup": true,
    "exclude": [
        "**/*+(index|.test|.spec|.e2e).ts"
    ],
    "hideGenerator": true,
    "listInvalidSymbolLinks": true,
    "plugin": "typedoc-neo-theme",
    "links": [],
    "outline": [],
    "search": [],
    "source": []
}
```

**Comment by Fleker** [comment]
Thanks. I have not tried v0.20.x yet but it seems like there are some breaking changes.

**Comment by muuvmuuv** [comment]
Read the migration guide: https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0

**Comment by Fleker** [comment]
There also seem to be multiple revisions and fixes, so once those patches are complete there may be fewer issues. Until then I'd advise folks to stay on 0.19.x with this theme.

**Comment by Fleker** [comment]
Among other changes, I have made the following in a test project:

1. Removed `ignoreCompilerErrors` and `excludeNotExported` entries from `typedoc.json`
2. Added `"exclude": ["./node_modules"]` to `typedoc.json`
2. Updated `yarn docs` to point to the current folder `typedoc --options typedoc.json --theme node_modules/typedoc-neo-theme/bin/default .`
