### ISSUE TITLE
Theme references `globals.html` which TypeDoc 0.20 does not emit

### ISSUE THREAD

**Issue by gnidan** [google/typedoc-neo-theme#67]
TypeDoc v0.20 now emits a file `modules.html`, which the default themes style as "Exports" instead of "Globals".

When specifying `outline` in typedoc.json, this theme hardcodes "Globals" in the outline, resulting in a broken href. This is hardcoded in the [default layout](https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/layouts/default.hbs#L31).

This theme should respect the new TypeDoc behavior and not generate links to files that don't exist.

**Comment by josh-renton** [comment]
+1

**Comment by Fleker** [comment]
Yes I do need to re-review this.
