### ISSUE TITLE
Can't get typedoc-neo-theme to work

### ISSUE THREAD

**Issue by bflemi3** [google/typedoc-neo-theme#74]
I'm not understanding how to run typedoc with your plugin. Your documentation says build the theme `yarn build:theme` and build the plugin `yarn build:plugin` then run typedoc with the plugin 

```
typedoc --theme ../../node_modules/typedoc-neo-theme/bin/default
```

`yarn build:theme` doesn't work, yarn doesn't recognize that as a script. So I navigate to `./node_modules/typedoc-neo-theme` and run `yarn build:theme`, but get errors that grunt doesn't exist in `./node_modules/.bin/grunt`.

So I `yarn` in `node_modules/typedoc-neo-theme` which feels like I'm doing something wrong. Then run `yarn build:theme` again and get a ton of cannot find module errors, probably because I'm running the script from within your plugin, not my directory. Here's the first error I'm seeing, for example
> ../@types/aws-lambda/index.d.ts(66,15): error TS2307: Cannot find module './trigger/cognito-user-pool-trigger/' or its corresponding type declarations.

---

If I try to just run typedoc (from my project root) with your plugin via 
```
./node_modules/.bin/typedoc --theme ../../node_modules/typedoc-neo-theme/bin/default
```

I get the following error
> Error: The plugin /Users/brandonfleming/dev/bubbles/node_modules/typedoc-neo-theme could not be loaded.
Info: Error: Cannot find module './bin/default/plugin'

So what am I doing wrong?

**Comment by Fleker** [comment]
The README might have some additional details for those who are cloning the source code rather than installing it. 

For using it in another project, such as a few libraries including [actions-on-google-nodejs](https://github.com/actions-on-google/actions-on-google-nodejs), the setup is a bit less work:

1. Provide the library [as a devDependency](https://github.com/actions-on-google/assistant-conversation-nodejs/blob/master/package.json#L58)
2. Use the `theme` parameter in the [typedoc command](https://github.com/actions-on-google/assistant-conversation-nodejs/blob/master/package.json#L25)

```
"scripts": {
    "docs": "typedoc --options typedoc.json --theme node_modules/typedoc-neo-theme/bin/default src/"
}
```

3. Run `yarn docs` or `npm run docs` to generate docs with this theme.

**Comment by bflemi3** [comment]
Thanks for the quick response @Fleker. I"m still getting the following exception
> The theme ./node_modules/typedoc-neo-theme/bin/default could not be found.

Don't I need to build the theme first? If so, that takes me back to my first problem where `yarn build:theme` and `yarn build:plugin` don't work.

**Comment by bflemi3** [comment]
Still getting the same issues from the root, can't build the theme.

> ../@types/aws-lambda/index.d.ts(66,15): error TS2307: Cannot find module './trigger/cognito-user-pool-trigger/' or its corresponding type declarations.

**Comment by Fleker** [comment]
Are you installing the package via NPM or are you cloning the repo?

**Comment by k88manish** [comment]
Is this package not available on yarn?

**Comment by bflemi3** [comment]
I installed via Yarn. 

I've moved back to just using typedoc out of the box. I'll close this issue.

**Comment by jessegeens** [comment]
I have the same issue:
* installed via npm: ` npm install -D typedoc-neo-theme --save`
* trying to run typedoc yields:
``` 
$ npx typedoc --theme ./node_modules/typedoc-neo-theme/bin/default --plugin typedoc-neo-theme
Error: Invalid structure in plugin typedoc-neo-theme, no load function found.
```
```
$ npx typedoc --theme typedoc-neo-theme                           
Error: Invalid structure in plugin typedoc-neo-theme, no load function found.
```

Any updates on what could be causing this?
